apiVersion: batch/v1
kind: Job
metadata:
  name: gores-producer-duplicate
  labels:
    app: gores-producer-duplicate
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: gores-producer-duplicate
    spec:
      restartPolicy: Never
      containers:
      - name: producer
        image: gores:latest
        imagePullPolicy: Never
        command: ["./gores", "-o", "produce", "-n", "300", "-idemp"]
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
